<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="viewrole.aspx.vb" Inherits="LMS_WEB_.viewrole" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
    </div>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" 
        BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="4" 
        DataKeyNames="rid" DataSourceID="SqlDataSource1" ForeColor="Black" 
        GridLines="Horizontal">
        <Columns>
            <asp:BoundField DataField="rid" HeaderText="rid" ReadOnly="True" 
                SortExpression="rid" />
            <asp:BoundField DataField="rname" HeaderText="rname" SortExpression="rname" />
        </Columns>
        <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
        <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
        <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F7F7F7" />
        <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
        <SortedDescendingCellStyle BackColor="#E5E5E5" />
        <SortedDescendingHeaderStyle BackColor="#242121" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConflictDetection="CompareAllValues" 
        ConnectionString="<%$ ConnectionStrings:LMSConnectionString %>" 
        DeleteCommand="DELETE FROM [role] WHERE [rid] = @original_rid AND (([rname] = @original_rname) OR ([rname] IS NULL AND @original_rname IS NULL))" 
        InsertCommand="INSERT INTO [role] ([rid], [rname]) VALUES (@rid, @rname)" 
        OldValuesParameterFormatString="original_{0}" 
        SelectCommand="SELECT * FROM [role]" 
        UpdateCommand="UPDATE [role] SET [rname] = @rname WHERE [rid] = @original_rid AND (([rname] = @original_rname) OR ([rname] IS NULL AND @original_rname IS NULL))">
        <DeleteParameters>
            <asp:Parameter Name="original_rid" Type="Int32" />
            <asp:Parameter Name="original_rname" Type="String" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="rid" Type="Int32" />
            <asp:Parameter Name="rname" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="rname" Type="String" />
            <asp:Parameter Name="original_rid" Type="Int32" />
            <asp:Parameter Name="original_rname" Type="String" />
        </UpdateParameters>
    </asp:SqlDataSource>
    </form>
</body>
</html>
