<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="viewpatient.aspx.vb" Inherits="LMS_WEB_.viewpatient" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
    </div>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" 
        BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="4" 
        DataKeyNames="p_id" DataSourceID="SqlDataSource1" ForeColor="Black" 
        GridLines="Horizontal">
        <Columns>
            <asp:BoundField DataField="p_id" HeaderText="p_id" ReadOnly="True" 
                SortExpression="p_id" />
            <asp:BoundField DataField="p_name" HeaderText="p_name" 
                SortExpression="p_name" />
            <asp:BoundField DataField="gender" HeaderText="gender" 
                SortExpression="gender" />
            <asp:BoundField DataField="dob" HeaderText="dob" SortExpression="dob" />
            <asp:BoundField DataField="phone" HeaderText="phone" SortExpression="phone" />
            <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
            <asp:BoundField DataField="address" HeaderText="address" 
                SortExpression="address" />
            <asp:BoundField DataField="aadhar" HeaderText="aadhar" 
                SortExpression="aadhar" />
            <asp:BoundField DataField="reg_date" HeaderText="reg_date" 
                SortExpression="reg_date" />
            <asp:BoundField DataField="ref_by" HeaderText="ref_by" 
                SortExpression="ref_by" />
        </Columns>
        <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
        <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
        <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F7F7F7" />
        <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
        <SortedDescendingCellStyle BackColor="#E5E5E5" />
        <SortedDescendingHeaderStyle BackColor="#242121" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConflictDetection="CompareAllValues" 
        ConnectionString="<%$ ConnectionStrings:LMSConnectionString %>" 
        DeleteCommand="DELETE FROM [patient] WHERE [p_id] = @original_p_id AND [p_name] = @original_p_name AND [gender] = @original_gender AND (([dob] = @original_dob) OR ([dob] IS NULL AND @original_dob IS NULL)) AND [phone] = @original_phone AND (([email] = @original_email) OR ([email] IS NULL AND @original_email IS NULL)) AND [address] = @original_address AND (([aadhar] = @original_aadhar) OR ([aadhar] IS NULL AND @original_aadhar IS NULL)) AND (([reg_date] = @original_reg_date) OR ([reg_date] IS NULL AND @original_reg_date IS NULL)) AND (([ref_by] = @original_ref_by) OR ([ref_by] IS NULL AND @original_ref_by IS NULL))" 
        InsertCommand="INSERT INTO [patient] ([p_id], [p_name], [gender], [dob], [phone], [email], [address], [aadhar], [reg_date], [ref_by]) VALUES (@p_id, @p_name, @gender, @dob, @phone, @email, @address, @aadhar, @reg_date, @ref_by)" 
        OldValuesParameterFormatString="original_{0}" 
        SelectCommand="SELECT * FROM [patient]" 
        UpdateCommand="UPDATE [patient] SET [p_name] = @p_name, [gender] = @gender, [dob] = @dob, [phone] = @phone, [email] = @email, [address] = @address, [aadhar] = @aadhar, [reg_date] = @reg_date, [ref_by] = @ref_by WHERE [p_id] = @original_p_id AND [p_name] = @original_p_name AND [gender] = @original_gender AND (([dob] = @original_dob) OR ([dob] IS NULL AND @original_dob IS NULL)) AND [phone] = @original_phone AND (([email] = @original_email) OR ([email] IS NULL AND @original_email IS NULL)) AND [address] = @original_address AND (([aadhar] = @original_aadhar) OR ([aadhar] IS NULL AND @original_aadhar IS NULL)) AND (([reg_date] = @original_reg_date) OR ([reg_date] IS NULL AND @original_reg_date IS NULL)) AND (([ref_by] = @original_ref_by) OR ([ref_by] IS NULL AND @original_ref_by IS NULL))">
        <DeleteParameters>
            <asp:Parameter Name="original_p_id" Type="Int32" />
            <asp:Parameter Name="original_p_name" Type="String" />
            <asp:Parameter Name="original_gender" Type="String" />
            <asp:Parameter DbType="Date" Name="original_dob" />
            <asp:Parameter Name="original_phone" Type="Decimal" />
            <asp:Parameter Name="original_email" Type="String" />
            <asp:Parameter Name="original_address" Type="String" />
            <asp:Parameter Name="original_aadhar" Type="Decimal" />
            <asp:Parameter DbType="Date" Name="original_reg_date" />
            <asp:Parameter Name="original_ref_by" Type="String" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="p_id" Type="Int32" />
            <asp:Parameter Name="p_name" Type="String" />
            <asp:Parameter Name="gender" Type="String" />
            <asp:Parameter DbType="Date" Name="dob" />
            <asp:Parameter Name="phone" Type="Decimal" />
            <asp:Parameter Name="email" Type="String" />
            <asp:Parameter Name="address" Type="String" />
            <asp:Parameter Name="aadhar" Type="Decimal" />
            <asp:Parameter DbType="Date" Name="reg_date" />
            <asp:Parameter Name="ref_by" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="p_name" Type="String" />
            <asp:Parameter Name="gender" Type="String" />
            <asp:Parameter DbType="Date" Name="dob" />
            <asp:Parameter Name="phone" Type="Decimal" />
            <asp:Parameter Name="email" Type="String" />
            <asp:Parameter Name="address" Type="String" />
            <asp:Parameter Name="aadhar" Type="Decimal" />
            <asp:Parameter DbType="Date" Name="reg_date" />
            <asp:Parameter Name="ref_by" Type="String" />
            <asp:Parameter Name="original_p_id" Type="Int32" />
            <asp:Parameter Name="original_p_name" Type="String" />
            <asp:Parameter Name="original_gender" Type="String" />
            <asp:Parameter DbType="Date" Name="original_dob" />
            <asp:Parameter Name="original_phone" Type="Decimal" />
            <asp:Parameter Name="original_email" Type="String" />
            <asp:Parameter Name="original_address" Type="String" />
            <asp:Parameter Name="original_aadhar" Type="Decimal" />
            <asp:Parameter DbType="Date" Name="original_reg_date" />
            <asp:Parameter Name="original_ref_by" Type="String" />
        </UpdateParameters>
    </asp:SqlDataSource>
    </form>
</body>
</html>
